CREATE TABLE FACULTY (
    FACULTY      CHAR(10)      NOT NULL PRIMARY KEY,
    FACULTY_NAME NVARCHAR(100) NULL
);

CREATE TABLE PULPIT (
    PULPIT      CHAR(10)      NOT NULL PRIMARY KEY,
    PULPIT_NAME NVARCHAR(100) NULL,
    FACULTY     CHAR(10)      NOT NULL FOREIGN KEY REFERENCES FACULTY(FACULTY)
);

CREATE TABLE TEACHER (
    TEACHER      CHAR(10)      NOT NULL PRIMARY KEY,
    TEACHER_NAME NVARCHAR(100) NULL,
    PULPIT       CHAR(10)      NOT NULL FOREIGN KEY REFERENCES PULPIT(PULPIT)
);

CREATE TABLE [SUBJECT] (
    [SUBJECT]    CHAR(10)      NOT NULL PRIMARY KEY,
    SUBJECT_NAME NVARCHAR(100) NULL,
    PULPIT       CHAR(10)      NOT NULL FOREIGN KEY REFERENCES PULPIT(PULPIT) ON DELETE CASCADE
);

CREATE TABLE AUDITORIUM_TYPE (
    AUDITORIUM_TYPE     CHAR(10)      NOT NULL PRIMARY KEY,
    AUDITORIUM_TYPENAME NVARCHAR(100) NULL
);

CREATE TABLE AUDITORIUM (
    AUDITORIUM          CHAR(10)      NOT NULL PRIMARY KEY,
    AUDITORIUM_NAME     NVARCHAR(100) NULL,
    AUDITORIUM_CAPACITY INT           NULL,
    AUDITORIUM_TYPE     CHAR(10)      NOT NULL FOREIGN KEY REFERENCES AUDITORIUM_TYPE(AUDITORIUM_TYPE)
);